In [9]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
from scipy import linalg


In [10]:
def Channel_Rayleigh(no_users, no_transmit, rayleigh_scale=None):
    """Returns a random, complex Rayleigh fading wireles channel 
    matrix of size (no_users, no_transmit). 
    
    'no_users = NK and no_transmit = NM'
    
    TODO: include seed option, to return same matrix for testing."""
    
    if rayleigh_scale is None:
        rayleigh_scale = 1
    else:
        None
    
    re_H = np.random.rayleigh(rayleigh_scale, (no_users, no_transmit))
    im_H = np.random.rayleigh(rayleigh_scale, (no_users, no_transmit))
    
    H = re_H + im_H*1J
    
    return H

H = Channel_Rayleigh(4,8)

print(np.around(H,decimals=2))

[[1.17+2.1j  1.07+0.86j 1.68+0.51j 0.78+0.65j 1.04+2.5j  1.49+1.47j
  0.28+1.4j  0.07+0.54j]
 [0.57+0.97j 1.92+1.47j 1.78+1.78j 2.28+1.22j 1.82+0.99j 0.78+1.62j
  0.2 +1.75j 1.43+1.47j]
 [0.94+0.65j 0.88+2.3j  0.74+1.66j 0.33+0.43j 1.42+1.23j 0.93+0.91j
  1.35+1.03j 0.4 +1.69j]
 [1.09+1.66j 0.29+1.62j 2.32+1.89j 0.53+1.46j 1.66+0.8j  1.91+0.58j
  1.29+1.4j  1.61+0.77j]]


In [21]:
def Precoder_Mat(channel_mat):
    """Given a wireless channel matrix, return zero-forcing precoder matrix.
    'P = H^\dagger (HH^\dagger)^{-1}'
    
    TODO: consider only the reduced, but then match dims with other functions."""
    
    channel_mat_h = channel_mat.conj().T
    
    Ueig_inv = np.linalg.inv(channel_mat @ channel_mat_h)
    
    P = channel_mat_h @ Ueig_inv
    return P

# Find out what that svd approx was
def Precoder_Mat_svd(channel_mat):
    """Given a wireless channel matrix, return zero-forcing precoder matrix,
    approximated by SVD.
    
    TODO: consider only the reduced, but then match dims with other functions."""
    
    D = np.zeros(channel_mat.shape)
    
    U, s, Vh = np.linalg.svd(channel_mat)
    
    for i in range(len(s)):
        D[i,i] = s[i]
    
    Uh = U.conj().T
    V = Vh.conj().T
    
    HHh_inv = np.linalg.inv(U @ D @ D.T @ Uh)
    
    print(np.around(HHh_inv, decimals=2), '\n')
    
    P = V @ D.T @ Uh @ HHh_inv
    
    return U, D, Vh, P

U, D, Vh, A = Precoder_Mat_svd(H)

P = Precoder_Mat(H)

print(np.around(P,decimals=2),'\n')


print(np.around(U, decimals=2), '\n', np.around(D,decimals=2), '\n', np.around(Vh,decimals=2))

[[ 0.16-0.j   -0.06+0.04j -0.02-0.09j -0.06+0.01j]
 [-0.06-0.04j  0.15-0.j   -0.08+0.07j -0.03-0.01j]
 [-0.02+0.09j -0.08-0.07j  0.27-0.j   -0.1 -0.03j]
 [-0.06-0.01j -0.03+0.01j -0.1 +0.03j  0.17+0.j  ]] 

[[ 0.06-0.12j -0.03+0.07j  0.02+0.08j  0.01-0.09j]
 [ 0.13+0.09j  0.04+0.03j  0.12-0.27j -0.23+0.01j]
 [ 0.06+0.13j -0.03-0.02j -0.06-0.05j  0.11-0.09j]
 [-0.09-0.j    0.28-0.06j -0.08+0.26j -0.07-0.16j]
 [-0.01-0.24j  0.07+0.08j -0.07-0.03j  0.02+0.1j ]
 [ 0.07-0.06j -0.1 -0.05j -0.02-0.05j  0.1 +0.11j]
 [-0.06+0.08j -0.13-0.13j  0.26+0.06j  0.03-0.04j]
 [-0.1 +0.04j  0.05-0.04j -0.08-0.11j  0.13+0.08j]] 

[[-0.46-0.j    0.7 -0.j   -0.36-0.j    0.41+0.j  ]
 [-0.56+0.06j -0.25+0.44j -0.13+0.52j -0.32-0.23j]
 [-0.43-0.02j -0.29-0.39j  0.03+0.1j   0.04+0.75j]
 [-0.53+0.08j -0.07-0.11j  0.37-0.66j -0.15-0.31j]] 
 [[9.98 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.85 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   2.24 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.54 0.   0.   0.   0.  ]] 
 

In [33]:
def Random_bit_string(length, layers):
    bits = np.random.binomial(n=1, p=0.5, size=(layers, length))
    return bits

def Modulate_bits():
    """ DO LATER"""
    s= []
    return s


Random_bit_string(10, 2)

array([[1, 0, 0, 0, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0]])

In [34]:
def QAM(size):
    """QAM modulation dictionaries"""
    
    size = int(size)
    
    mapping_table_2 = {
        (0) : -1,
        (1) : +1
    }
    
    mapping_table_4 = {
        (0,0) : -1-1J,
        (0,1) : -1+1J,
        (1,1) : 1+1J,
        (1,0) : 1-1J
    }
    
    mapping_table_16 = {
        (0,0,0,0) : -3-3j,
        (0,0,0,1) : -3-1j,
        (0,0,1,0) : -3+3j,
        (0,0,1,1) : -3+1j,
        (0,1,0,0) : -1-3j,
        (0,1,0,1) : -1-1j,
        (0,1,1,0) : -1+3j,
        (0,1,1,1) : -1+1j,
        (1,0,0,0) :  3-3j,
        (1,0,0,1) :  3-1j,
        (1,0,1,0) :  3+3j,
        (1,0,1,1) :  3+1j,
        (1,1,0,0) :  1-3j,
        (1,1,0,1) :  1-1j,
        (1,1,1,0) :  1+3j,
        (1,1,1,1) :  1+1j
    }
    
#     ADD:
#     mapping_table_64 = {
        
#     }
    
    get = {
        2 : mapping_table_2,
        4 : mapping_table_4,
        16 : mapping_table_16
    }
    
    return get[size]

(-3-3j)


In [49]:
A = np.linalg.inv(H @ H.conj().T).conj().T @ H @ H.conj().T @ np.linalg.inv(H @ H.conj().T)

print(np.around(A,decimals=2), '\n')

print(np.around(np.linalg.inv(H@H.conj().T),decimals=2))

np.around(A,decimals=2) == np.around(np.linalg.inv(H@H.conj().T),decimals=2)


[[ 0.16-0.j   -0.06+0.04j -0.02-0.09j -0.06+0.01j]
 [-0.06-0.04j  0.15-0.j   -0.08+0.07j -0.03-0.01j]
 [-0.02+0.09j -0.08-0.07j  0.27+0.j   -0.1 -0.03j]
 [-0.06-0.01j -0.03+0.01j -0.1 +0.03j  0.17+0.j  ]] 

[[ 0.16-0.j   -0.06+0.04j -0.02-0.09j -0.06+0.01j]
 [-0.06-0.04j  0.15-0.j   -0.08+0.07j -0.03-0.01j]
 [-0.02+0.09j -0.08-0.07j  0.27-0.j   -0.1 -0.03j]
 [-0.06-0.01j -0.03+0.01j -0.1 +0.03j  0.17-0.j  ]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
power = np.linspace(-5,-1, 5)
print(power)
np.sum(2**power)


[-5. -4. -3. -2. -1.]


0.96875

In [58]:
np.log2(np.sqrt(2))

0.5000000000000001

In [63]:
vec = np.random.rand(10)
print(vec)

[0.97958846 0.79244067 0.17011693 0.48545375 0.440497   0.75275675
 0.91765698 0.21951442 0.583396   0.11520599]
